### PR TITLE
Support Contao 4.13+

### PR DESCRIPTION
**Pull request by aschempp**
I think it would make sense to have one version that support the latest LTS as well as the current Contao versions. Since 4.13 contains (almost) all relevant changes that Contao 5 requires, this shouldn't be a problem to achieve 😊

### CODE REVIEW

**Comment by stefanheimes** [comment]
@aschempp it would make things easier, that's true. I will check it and rewrite some parts to allow both versions. I think that most of the changes will run in Contao 4 and 5.

**Comment by aschempp** [comment]
I'll follow-up with some fixes as well, but I currently can't install on my 4.13 at all 😅
Since this is a feature branch and WIP I assume(d) we can merge stuff and fix what comes up? 🙃

**Comment by stefanheimes** [comment]
Sure, if there is a problem, just make a PR or tell me. I will see if I can fix it. In the end, this will the new 3.6.0 until then this is the beta/alpha/test branch for it.

**Comment by stefanheimes** [comment]
@aschempp Update is merged and the test workflow is updated as well.

**Pull request merged**
